#include "rtfs_config.h"

#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_LIBBLOCK
#define CONFIGURE_APPLICATION_NEEDS_CLASSIC_API_SERVICES
#define CONFIGURE_MAXIMUM_EVENTS 4

#define CONFIGURE_FILESYSTEM_DOSFS
#define CONFIGURE_MAXIMUM_FILE_DESCRIPTORS 512
#define CONFIGURE_DRIVER_AMB_RAM_DISK

#define CONFIGURE_UNLIMITED_OBJECTS
#define CONFIGURE_UNIFIED_WORK_AREAS
#define CONFIGURE_MAXIMUM_SEMAPHORES RTEMS_DOSFS_SEMAPHORES_PER_INSTANCE
#define CONFIGURE_RTEMS_INIT_TASKS_TABLE
#ifdef ENABLE_UNIT_TEST
#define CONFIGURE_INIT_TASK_STACK_SIZE (256 * 1024)
#else
#define CONFIGURE_INIT_TASK_STACK_SIZE (64 * 1024)
#endif
#define CONFIGURE_INIT_TASK_PRIORITY 100

#define CONFIGURE_MAXIMUM_TIMERS 8

#define CONFIGURE_MEMORY_SIZE (256 * 1024 * 1024) // 256 MB。

#define CONFIGURE_INIT


#include <rtems/confdefs.h>
